name: dbos-fastapi-template
language: python
runtimeConfig:
  start:
    - fastapi run app/main.py
database:
  hostname: userdb-a6f1fc79-e474-4e44-895c-fbaf0c286202.cvc4gmaa6qm9.us-east-1.rds.amazonaws.com
  port: 5432
  username: dbos_user
  password: password
  migrate:
    - echo 'No migrations specified'
  local_suffix: true
telemetry:
  logs:
    logLevel: INFO
